version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:pass@db:5432/avito?sslmode=disable
    command: [ "/app/entrypoint.sh" ]
    volumes:
      - ./schema/migrations:/app/schema/migrations

    ports:
      - "8080:8080"

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: avito
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
